# Generated by Django 3.1.2 on 2021-01-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_item_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
