# Generated by Django 3.1.5 on 2021-01-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210105_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default='A', upload_to='media/uploads/'),
            preserve_default=False,
        ),
    ]
