# Generated by Django 3.1.5 on 2021-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210127_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.CharField(default='a.a', max_length=100),
            preserve_default=False,
        ),
    ]
