# Generated by Django 3.1.2 on 2020-11-06 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='country',
            new_name='shipping_country',
        ),
    ]
