# Generated by Django 3.1.2 on 2020-11-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201106_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.TextField()),
                ('file', models.FilePathField(match='*\\.pdf', path='/files')),
            ],
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='shipping_address',
            field=models.CharField(default='morenka', max_length=100),
            preserve_default=False,
        ),
    ]
