# Generated by Django 3.1.2 on 2020-11-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20201109_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
