# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - buggy-app

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    types: opened
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: |
          pip install wapiti3
          wapiti -u https://bugysite.azurewebsites.net/ -m "common, csrf, htaccess, xxe" -f json -o output.json
          cat output.json | jq .vulnerabilities
        
