# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - buggy-app

on:
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  SCA:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Perform SAST Snyk scan.
        run: |
          docker run --rm --env SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} -v $PWD:/buggy-site snyk/snyk:python-3.8 snyk code test /buggy-site

      - name: Perform SCA Snyk scan.
        run: |
          docker run --rm --env SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} --env COMMAND="pip install -r /buggy-site/requirements.txt" \
          -v $PWD:/buggy-site snyk/snyk:python-3.8 snyk test --file=/buggy-site/requirements.txt --json-file-output=/buggy-site/output.json
