# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - buggy-app

on:
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Perform SCA Snyk scan.
        run: |
          docker pull snyk/snyk:python
          docker run --rm --env ${{ secrets.SNYK_TOKEN }} --env COMMAND="pip install -r /app/requirements.txt" -v $(PWD):/app snyk/snyk:python snyk test --file=/app/requirements.txt
